ibmcloud_api_key = ""
region = "us-south"
cos_ibm_cloud_api_key = ""
cos_endpoint_url = "https://s3.us-south.cloud-object-storage.appdomain.cloud"
cos_instance_id = ""
rag_app_api_key = ""
wx_url = "https://us-south.ml.cloud.ibm.com"
wx_project_id = ""
wxd_username = ""
wxd_password = ""
wxd_url = "https://<host>:<port>"
wd_api_key = ""
wd_url = ""

resource_group = ""
project_name = ""
source_revision = ""
cr_namespace = ""